convert -background none -fill black -font font.ttf -pointsize 300 label:"1" img/1.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"2" img/2.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"3" img/3.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"4" img/4.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"5" img/5.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"6" img/6.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"7" img/7.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"8" img/8.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"9" img/9.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"10" img/10.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"11" img/11.png
convert -background none -fill black -font font.ttf -pointsize 300 label:"12" img/12.png